"""
Django settings for moromafinance project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from celery.schedules import crontab
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Environment loading (zero-dependency .env loader)
# Reads BASE_DIR/.env (git-ignored) into os.environ without overriding values
# already present in the real environment. Keeps secrets out of source control.
# ---------------------------------------------------------------------------
def _load_dotenv(path):
    try:
        with open(path, 'r', encoding='utf-8') as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, value = line.partition('=')
                key = key.strip()
                value = value.strip()
                # A quoted value is taken verbatim, so secrets are free to
                # contain '#'. An unquoted one ends at the first whitespace-
                # preceded '#', which is the usual .env inline-comment rule --
                # without this, `DB_USER=root  # note` sets the user to the
                # whole line, including the note.
                if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                    value = value[1:-1]
                else:
                    for idx, char in enumerate(value):
                        if char == '#' and idx > 0 and value[idx - 1].isspace():
                            value = value[:idx]
                            break
                    value = value.strip()
                os.environ.setdefault(key, value)
    except FileNotFoundError:
        pass


_load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-change-me-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=False)

#change in production environment for ip and domain(s)
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Origins Django will trust for CSRF (required behind an HTTPS proxy on Django 4+).
CSRF_TRUSTED_ORIGINS = _env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost,http://127.0.0.1',
)

# ---------------------------------------------------------------------------
# Production security hardening. Applies whenever DEBUG is off. Items that can
# cause redirect loops behind a TLS-terminating proxy are gated behind their
# own env flags so they can be switched on only once nginx is confirmed to
# forward the X-Forwarded-Proto header.
# ---------------------------------------------------------------------------
# SAMEORIGIN (not Django's DENY default) so the app can embed its OWN PDFs — the
# CDN / LAS / Loan Statement on-screen previews use a same-origin iframe. Set
# globally (not just under `if not DEBUG`) so the previews also work with
# DEBUG=True. Cross-origin framing is still blocked, so clickjacking protection
# is retained.
X_FRAME_OPTIONS = 'SAMEORIGIN'

if not DEBUG:
    # Secure cookies require HTTPS: the browser will not send them over plain
    # HTTP, which silently breaks login/CSRF. They default to True (correct for
    # production) but can be turned off for an HTTP-only preview on a bare IP.
    # TURN THESE BACK ON (remove the .env overrides) as soon as TLS is in place.
    SESSION_COOKIE_SECURE = _env_bool('DJANGO_SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = _env_bool('DJANGO_CSRF_COOKIE_SECURE', default=True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    # nginx terminates TLS and proxies plain HTTP to gunicorn; trust its header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Enable only after confirming nginx sets `proxy_set_header X-Forwarded-Proto $scheme;`
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', default=False)

    # HSTS: start at 0, raise gradually (e.g. 3600, then 31536000) once happy.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
    SECURE_HSTS_PRELOAD = _env_bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)


#site settings
SITE_NAME = 'Moroma Finance'
# Absolute base URL of this deployment. Used to build links and to resolve
# static asset URLs inside generated PDFs — set DJANGO_DOMAIN in .env to the
# real MOROMA domain in production (e.g. https://www.moromafinance.com.pg).
DOMAIN = os.environ.get('DJANGO_DOMAIN', 'http://localhost:8000')  # reduces Sites framework db calls
DOMAIN_DNS = os.environ.get('DJANGO_DOMAIN_DNS', 'moromafinance.com.pg')  # email = f'{random_email}@{settings.DOMAIN_DNS}' in staff.views.py
PREFIX = os.environ.get('MOROMA_CODE_PREFIX', 'MFX')  # prefix for all MOROMA-generated codes

MAIN_COLOR = '#0f6e3a' # MOROMA green (client logo/letterhead, see client_documents/)

# DO NOT FORGET : 'django.contrib.humanize', in apps 

SUPPORT_EMAIL = 'sales@moromafinance.com.pg'
ADMIN_RECEIVER = 'mktosa@moromafinance.com.pg' #main admin (Moses Tosa) to receive notifications
TEST_RECEIVER = os.environ.get('TEST_RECEIVER', 'mktosa@moromafinance.com.pg') # development TEST admin to receive notifications
TEST_USER = 'zyakap@outlook.com' #TEST user to receive notifications

#DCC (Dinau Control Centre credit bureau). These identify THIS lender to the
# bureau — they must be MOROMA's own. Left blank until MOROMA is onboarded; set via
# env. DCC is opt-in (see dcc_enabled / DCC_API_KEY) so blank values stay dormant.
LUID = os.environ.get('DCC_TENANT_LUID', '')
DCC_PROFILE_ID = os.environ.get('DCC_PROFILE_ID', '')
DCC_ENDPOINT = os.environ.get('DCC_ENDPOINT', 'www.dinaucontrolcentre.com')
# Scheme for outbound bureau calls. Defaults to https; set DCC_SCHEME=http only
# when the bureau has no TLS listener (e.g. serves plain HTTP on port 80). Note
# that http sends the X-API-KEY in cleartext — prefer getting TLS on the bureau.
DCC_SCHEME = os.environ.get('DCC_SCHEME', 'https')

#Public Service Deduction Code (assigned to the lender by the payroll authority).
# 'DMAWE' is printed on Moroma's in-use loan application form (client_documents/).
ALESCO_DC = os.environ.get('ALESCO_DC', 'DMAWE')
COMPANY_NAME = 'Moroma Finance Ltd'
LOAN_TYPES = 1

INTEREST_TYPE = 'CUSTOM'
FIXED_INTEREST_RATE = 0.2
VARIABLE_INTEREST_RATE = 0.0125

#loan application
PROCESSING_FEE_CHARGABLE = 'YES'
PROCESSING_FEE = Decimal(0.0)
LOAN_APPLICATION_FEE = Decimal(0.0)
LOAN_MAX_AMOUNT = Decimal(5000.00)
LOAN_MIN_AMOUNT = Decimal(500.00)
DEFAULT_INTEREST = Decimal(20.00)
DEFAULT_INTEREST_RATE = Decimal(0.2)
DEFAULT_INTEREST_CALCULATION_MERCY_DAYS = 2

#minmax_settings — per the published MOROMA repayment schedule (K500–K5,000 in
# K50 steps, 7–36 fortnights; see REPAYMENT_TABLE in custom/functions.py)
MIN_FN = 7
MAX_FN = 36
MIN_AMOUNT = 500
MAX_AMOUNT = 5000
INCREMENT_AMOUNT = 50
INCREMENT_FN = 1

#REPAYMENT SETTINGS
TOTAL_ALLOWABLE_TOEAS = Decimal(0.50)
LOAN_COMPLETION_BALANCE = Decimal(5.00)


# NOTE ON INTEREST
# Moroma Finance interest is NOT a flat rate and is not configured here. It is
# set solely by the published repayment schedule in custom/functions.py
# (REPAYMENT_TABLE, generated from static_files/clientfiles/RepaymentTable.pdf),
# where each amount/term cell already has the interest baked in. The rate rises
# with the term (7 fortnights ≈ 28% … 36 fortnights ≈ 144%).
# The schedule IS Moroma's own ("1 Updated Ded Sch 2026.pdf", effective 1 Dec
# 2025) — see custom/functions.py and static_files/clientfiles/RepaymentTable.pdf.
#
# The former INTEREST1/2/3, FIXED_INTEREST_RATE and VARIABLE_INTEREST_RATE
# constants were removed: they were unused by any code and documented a
# 30/40/50% banding that contradicts the actual schedule.

#BANK ACCOUNT INFORMATION
# FALLBACKS for get_bank_config() when the bank fields in Settings ->
# AdminSettings are empty. Values below come from Moroma's own in-use loan
# application form (client_documents/): "BSP Waterfront Branch Cheque Account
# No. 7016639473". Verify with the client at go-live; the admin Settings screen
# overrides these.
BANK1 = 'BSP'
BANK1_ACC_NAME = 'Moroma Finance Ltd'
BANK1_ACC_NUM = '7016639473'
BANK1_BRANCH = 'Waterfront'
BANK1_BSB = ''
SWIFT = ''

#BANK ACCOUNT INFORMATION
BANK2 = ''
BANK2_ACC_NAME = ''
BANK2_ACC_NUM = ''
BANK2_BRANCH = ''
BANK2_BSB = ''

#email addresses
ADMIN_EMAILS = ['mktosa@moromafinance.com.pg']
APPLICATION_FORM_EMAIL = ['sales@moromafinance.com.pg']
FUNDING_NOTICE_EMAIL = ['mktosa@moromafinance.com.pg']
REPAYMENT_EMAIL = ['sales@moromafinance.com.pg']
REPORTS_EMAIL = ['mktosa@moromafinance.com.pg']
DEFAULTS_EMAIL = ['mktosa@moromafinance.com.pg']
NOTIFICATION_EMAILS = ['mktosa@moromafinance.com.pg']

DIRECTORS = []

DEFAULT_SENDER_EMAIL = 'Moroma Finance <sales@moromafinance.com.pg>'
#emails
REPLY_TO_EMAIL = 'sales@moromafinance.com.pg'
CC_EMAILS = []
BCC_EMAILS = []


#LOAN HANDLING
SYSTEM_TYPE = 'ONE_LOAN_PER_CLIENT' #one statement for one client with all loans treated as one 
MULTIPLE_LOANS = 'YES' #additional applications can be accepted with a current running loan

# for userprofile model to work
AUTH_USER_MODEL = 'accounts.User'






# Application definition
INSTALLED_APPS = [
    # 'jet.dashboard',
    # 'jet',
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'django_select2',
    'django_recaptcha',
    'ckeditor',
    'ckeditor_uploader',
    'wkhtmltopdf',
    'crispy_forms',
    'crispy_bootstrap5',  # Forgetting this was probably your error
    'fontawesomefree',
    'material',
    'import_export',
    'accounts',
    'admin1',
    'loan', 
    'staff',
    'message',
    'support',
    'custom',
    'api',
    'report',
    'dcc',
    'referral',
    'manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    '127.0.0.1',
]

# Debug toolbar is a development-only tool; never load it in production.
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']

ROOT_URLCONF = 'moromafinance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin1.context_processors.appearance',
            ],
        },
    },
]

WSGI_APPLICATION = 'moromafinance.wsgi.application'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# WKHTMLTOPDF
WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'

# HTML TO PDF
WKHTMLTOPDF_CMD_OPTIONS = {
    'quiet': True,
}

if os.name != 'nt':
    WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'
else:
    WKHTMLTOPDF_DEBUG = True

# WeasyPrint fallback (used when wkhtmltopdf is absent). gunicorn runs under
# systemd's PATH, which does not include the virtualenv's bin/, so a bare
# shutil.which('weasyprint') finds nothing there even though the package is
# installed. Point at the running interpreter's own bin/ so the fallback
# resolves whatever the PATH is; override with WEASYPRINT_CMD in .env.
WEASYPRINT_CMD = os.environ.get(
    'WEASYPRINT_CMD',
    os.path.join(os.path.dirname(sys.executable), 'weasyprint'),
)

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.environ.get('DB_NAME', 'moromafinance'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
# Project input formats: date fields accept every format offered in
# Settings -> Dates (see moromafinance/formats/en/formats.py).
FORMAT_MODULE_PATH = 'moromafinance.formats'
TIME_ZONE = 'Etc/GMT-10'
USE_I18N = True
USE_TZ = True
DATE_INPUT_FORMATS = ['%d-%m-%Y']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#Static Settings
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', '/root/moromafinance/static/')  #activate when on server environment
#STATIC_ROOT = 'static'   #comment out when on server
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_files'),
]

#MEDIA Conf
# Served by the authenticated `protected_media` view at /media/<path> (see
# moromafinance/urls.py + media_views.py). Must match that route — a mismatch
# (e.g. '/uploads/') makes every FileField .url 404 in production because
# nothing serves /uploads/ when DEBUG=False.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')   #check previous settings if media uploads dont work MEDIA_ROOT = 'uploads'

# When True, the authenticated /media/<path> view delegates byte-streaming to
# nginx via X-Accel-Redirect (requires the `internal` location, see media_views.py).
# Leave False until nginx is configured; the view then streams files itself.
USE_X_ACCEL_REDIRECT = _env_bool('USE_X_ACCEL_REDIRECT', default=False)

# Cap in-memory upload handling; larger files stream to a temp file on disk.
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024   # 15 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024    # 5 MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cache — filesystem-based so it is shared across all gunicorn workers (the
# default LocMemCache is per-process, which would make rate limiting per-worker).
# Switch to a Redis backend here once Redis is running for better performance.
CACHE_DIR = BASE_DIR / 'cache'
os.makedirs(CACHE_DIR, exist_ok=True)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(CACHE_DIR),
    }
}

# EMAIL SERVER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'sales@moromafinance.com.pg')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
# Cap each SMTP send so one hung mail connection can never freeze a request
# (bulk flows like the Alesco confirm send one email per line).
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# celery settings
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_TIMEZONE = 'Etc/GMT-10'

# When the Celery worker/beat are switched off, run tasks inline (eagerly) so
# on-demand jobs like bulk messaging still execute instead of queueing forever.
# Set CELERY_TASK_ALWAYS_EAGER=False in .env once a worker is running again.
CELERY_TASK_ALWAYS_EAGER = _env_bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_EAGER_PROPAGATES = False

CELERY_BEAT_SCHEDULE = {

    # Weekly portfolio PDF emailed to the configured admin recipients (see
    # report.tasks.weekly_report). Monday 7:30 AM local time.
    'weekly_report': {
        'task': 'report.tasks.weekly_report',
        'schedule': crontab(day_of_week=1, hour=7, minute=30),
    },
    'payments_expected_today': {
        'task': 'loan.tasks.payments_expected_today',
        'schedule': 2*60,
    },

    # 'reminded_today_reset' removed — the task loan.tasks.reminded_today_reset
    # does not exist, so beat would raise "Received unregistered task" each run.
    'default_classification': {
        'task': 'loan.tasks.default_classification',
        'schedule': 10*60,
    },

    #send repayment reminder
    'auto_send_repayment_reminder': {
        'task': 'loan.tasks.auto_send_repayment_reminder',
        'schedule': crontab(hour=8, minute=50), 
    },

    #run defaults
    'auto_run_defaults': {
        'task': 'loan.tasks.auto_run_defaults',
        'schedule': crontab(minute='*/30'), 
    }#,

    #run test
    #'auto_send_test_email': {
    #    'task': 'loan.tasks.auto_send_test_email',
    #    'schedule': crontab(hour='*/35'), 
    #}

}

#recaptcha
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', '')
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', '')
RECAPTCHA_RESPONSE_KEY = 'g-recaptcha-response'
RECAPTCHA_DOMAIN = 'www.recaptcha.net'

# ---------------------------------------------------------------------------
# Logging — once DEBUG is off, this is the only visibility into errors.
# ---------------------------------------------------------------------------
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)
LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'moromafinance.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        # Email server errors to admins once DEBUG is off (optional).
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

#django rest framework
REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    # Fail closed: endpoints must opt in to access explicitly.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Shared secret for machine-to-machine API access (DCC credit-bureau sync).
# Set DCC_API_KEY in .env. The external client must send it as the X-API-KEY header.
DCC_API_KEY = os.environ.get('DCC_API_KEY', '')

# Verify the DCC bureau's TLS certificate on outbound credit-check calls.
# Leave True in production; set DCC_VERIFY_SSL=False only if the bureau is on
# a self-signed certificate.
DCC_VERIFY_SSL = _env_bool('DCC_VERIFY_SSL', default=True)
DCC_ALLOW_HTTP_FALLBACK = _env_bool('DCC_ALLOW_HTTP_FALLBACK', default=False)

#CKEditor Settings
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'Basic',
    },
}

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Moroma Finance",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Moroma Finance",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": 'Moroma Finance',

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": None,

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Moroma Finance",

    # Copyright on the footer
    "copyright": "Moroma Finance Ltd",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index",
            "permissions": ["auth.view_user"]},

        # external url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "mailto:sales@moromafinance.com.pg", "new_window": True},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

## JET THEMES
'''
JET_THEMES = [
    {
        'theme': 'default', # theme folder name
        'color': '#47bac1', # color of the theme's button in user menu
        'title': 'Default' # theme title
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green',
        'font-size': '20px',
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

'''
