# Generated by Django 6.0.7 on 2026-07-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(choices=[(500, 500), (700, 700), (900, 900), (1100, 1100), (1300, 1300), (1500, 1500), (1700, 1700), (1900, 1900), (2100, 2100), (2300, 2300), (2500, 2500), (2700, 2700), (2900, 2900), (3000, 3000)], decimal_places=2, max_digits=8, null=True, verbose_name='LOAN AMOUNT:'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='number_of_fortnights',
            field=models.IntegerField(choices=[(5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26)], null=True, verbose_name='Number of Fortnights:'),
        ),
    ]
