# Generated by Django 6.0.7 on 2026-08-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_alter_loan_amount_alter_loan_number_of_fortnights'),
        ('loan', '0008_blackroseimport'),
    ]

    operations = [
    ]
