# Generated by Django 5.2.16 on 2026-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dcc_score_and_optional_kyc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dcc_dsr_band',
            field=models.CharField(blank=True, help_text='HEALTHY / CAUTION / OVER_LIMIT / CRITICAL / UNKNOWN, per DCC affordability policy.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dcc_dsr_percent',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Debt Service Ratio: what the client repays across ALL lenders as a percentage of verified income, per DCC.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dcc_headroom',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional fortnightly repayment DCC assesses this client can still afford.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dcc_velocity_level',
            field=models.CharField(blank=True, help_text='NORMAL / ELEVATED / HIGH — DCC loan-stacking verdict at the last check.', max_length=10, null=True),
        ),
    ]
