# Generated by Django 5.2.16 on 2026-08-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_alter_adminsettings_dcc_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_affordability_enabled',
            field=models.CharField(blank=True, choices=[('YES', 'YES - Decline applications the client cannot service'), ('NO', 'NO - Do not check affordability')], default='NO', help_text='Before approving, ask DCC whether the client can service the proposed repayment given everything they already repay to other lenders. Applications above the debt-service limit are declined automatically.', max_length=3, null=True, verbose_name='Enforce DCC Affordability (DSR):'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_auto_report_defaults',
            field=models.CharField(blank=True, choices=[('YES', 'YES - File a default notice automatically'), ('NO', 'NO - Report defaults manually')], default='NO', help_text='When a loan is classified as DEFAULTED, automatically file a formal default notice with the bureau. Listing a borrower is a deliberate act, so DCC still runs its notification and grace period before the default appears on their file.', max_length=3, null=True, verbose_name='Auto-Report Defaults to DCC:'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_block_on_no_income',
            field=models.BooleanField(default=False, help_text='When DCC holds no verified income for the client, affordability cannot be assessed. ON declines the application; OFF lets it through for manual review (the application is still flagged).', verbose_name='Decline When Income Cannot Be Verified:'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_default_report_after_days',
            field=models.PositiveIntegerField(default=30, help_text='Only file the notice once the loan has been in default for at least this many days, so a short payroll delay is never reported as a default.', verbose_name='Report Defaults After (days):'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_max_dsr_percent',
            field=models.PositiveIntegerField(default=40, help_text="Total fortnightly repayments across ALL lenders (including the new loan) must stay below this percentage of the client's verified income.", verbose_name='Maximum Debt Service Ratio (%):'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_registration_min_score',
            field=models.PositiveIntegerField(default=300, help_text='New clients scoring below this are held for manual review instead of being activated automatically.', verbose_name='Minimum DCC Score at Registration:'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_screen_registration',
            field=models.CharField(blank=True, choices=[('YES', 'YES - Check the bureau when a client registers'), ('NO', 'NO - Do not screen at registration')], default='NO', help_text='Run a DCC benchmark-score check as soon as a client registers, so bad risk is caught at the door rather than at loan application. Each check is billed at the DCC rating-check price.', max_length=3, null=True, verbose_name='Screen New Clients Against DCC:'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='dcc_stacking_action',
            field=models.CharField(blank=True, choices=[('IGNORE', 'Ignore - no action'), ('FLAG', 'Flag for manual review'), ('DECLINE', 'Decline automatically')], default='FLAG', help_text='What to do when DCC reports the client is shopping at several lenders at once or has taken multiple loans recently — the pattern that precedes most defaults.', max_length=10, null=True, verbose_name='On Loan-Stacking Alert:'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='admin_email_addresses',
            field=models.CharField(blank=True, default='sales@moromafinance.com.pg', help_text='Email Addresses that will receive system admin notifications. Enter email addresses separated by a comma. Eg: info@moromafinance.com.pg,admin@moromafinance.com.pg. Make sure there are no spaces after the comma', max_length=250, verbose_name='Admin Email Addresses:'),
        ),
    ]
