# Generated by Django 6.0.7 on 2026-08-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_alter_adminsettings_dcc_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='admin_email_addresses',
            field=models.CharField(blank=True, default='admin@moromafinance.com', help_text='Email Addresses that will receive system admin notifications. Enter email addresses separated by a comma. Eg: info@moromafinance.com.pg,admin@moromafinance.com.pg. Make sure there are no spaces after the comma', max_length=250, verbose_name='Admin Email Addresses:'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='default_from_email',
            field=models.CharField(blank=True, default='admin@moromafinance.com', help_text='Email Address that will send all notifications to the user.', max_length=100, verbose_name='Default From Email:'),
        ),
    ]
