# Generated by Django 6.0.7 on 2026-08-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_alter_adminsettings_admin_email_addresses_and_more'),
        ('admin1', '0006_dcc_affordability_settings'),
    ]

    operations = [
    ]
