# Generated by Django 6.0.7 on 2026-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_merge_20260804_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='role_staff_can_borrow',
            field=models.CharField(blank=True, choices=[('YES', 'YES - Staff may be selected as the client on a loan'), ('NO', 'NO - Hide staff from the client list')], default='NO', help_text='Staff members have a client profile of their own, which otherwise shows up in the client dropdown when creating a loan. Leave this off unless staff are allowed to borrow.', max_length=3, null=True, verbose_name='Staff As Borrowers:'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(choices=[('AROB', 'AROB'), ('CENTRAL', 'CENTRAL'), ('ENGA', 'ENGA'), ('EAST SEPIK', 'EAST SEPIK'), ('EHP', 'EHP'), ('ENB', 'ENBP'), ('GULF', 'GULF'), ('HELA', 'HELA'), ('JIWAKA', 'JIWAKA'), ('MADANG', 'MADANG'), ('MANUS', 'MANUS'), ('MILNE BAY', 'MILNE BAY'), ('MOROBE', 'MOROBE'), ('NCD', 'NCD'), ('NEW IRELAND', 'NEW IRELAND'), ('ORO', 'ORO'), ('SHP', 'SHP'), ('SIMBU', 'SIMBU'), ('WESTERN', 'WESTERN'), ('WEST SEPIK', 'WEST SEPIK'), ('WHP', 'WHP'), ('WNB', 'WNBP')], max_length=20),
        ),
    ]
